apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c52xep97u-go
  janus-idp.io/tekton: c52xep97u-go
  backstage.io/kubernetes-id: c52xep97u-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c52xep97u-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
